name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        add-http-endpoint: [yes, no]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests add_http_endpoint=${{ matrix.add-http-endpoint }}
      run: sbt ';set g8Properties in g8 in Test ~= { _ ++ Map("add_http_endpoint" -> "${{ matrix.add-http-endpoint }}") }; test'